export const email_priority_keywords = {
    1: new Set([
        "FYI",
        "newsletter",
        "update",
        "greetings",
        "notification",
        "announcement",
        "promotion",
        "subscription",
        "reminder",
        "offer",
        "welcome",
        "thanks",
        "summary",
        "recap",
        "alert",
        "digest",
        "news",
        "event",
        "survey reminder",
        "advertisement",
        "holiday",
        "invitation",
        "seasonal",
        "community",
        "webinar",
        "charity",
        "feedback request",
        "monthly report",
        "weekly update",
    ]),
    2: new Set([
        "discussion",
        "follow-up",
        "query",
        "feedback",
        "meeting",
        "review",
        "proposal",
        "inquiry",
        "survey",
        "agenda",
        "chat",
        "notes",
        "team",
        "coordinate",
        "input",
        "suggestion",
        "brainstorm",
        "comment",
        "request",
        "collaboration",
        "progress",
        "presentation",
        "check-in",
        "questions",
        "internal update",
        "task update",
        "weekly agenda",
        "status report",
    ]),
    3: new Set([
        "action required",
        "deadline",
        "urgent",
        "approval needed",
        "payment due",
        "contract",
        "submission",
        "report",
        "invoice",
        "confirmation",
        "escalation",
        "decision",
        "priority",
        "task",
        "pending",
        "compliance",
        "review required",
        "reconciliation",
        "budget",
        "performance",
        "audit request",
        "client request",
        "deliverable",
        "timeline",
        "milestone",
        "project update",
        "meeting confirmation",
        "policy change",
    ]),
    4: new Set([
        "critical",
        "emergency",
        "incident",
        "immediate attention",
        "breach",
        "lawsuit",
        "audit",
        "security",
        "termination",
        "crisis",
        "failure",
        "alert critical",
        "urgent escalation",
        "legal",
        "violation",
        "shutdown",
        "fraud",
        "investigation",
        "malware",
        "cyberattack",
        "compliance breach",
        "law enforcement",
        "court notice",
        "subpoena",
        "financial risk",
        "contract breach",
        "system outage",
        "data loss",
        "natural disaster",
    ]),
}

